# generate settings
name: base7
gpu_ids: [0]
train: ~

# datasets
datasets:
  train:
    dataroot_HR: /content/datasets/faces/original
    dataroot_LR: /content/datasets/faces/XN
    filename_path: /content/datasets/faces/faces.txt
    patch_size: 256
    batch_size: 16
    enlarge_times: 1
  val:
    dataroot_HR: /content/datasets/faces_val/original
    dataroot_LR: /content/datasets/faces_val/XN
    filename_path: /content/datasets/faces_val/faces.txt
    enlarge_times: 1

# networks
networks:
  which_model: base7
  scale: 4
  in_channels: 3
  num_fea: 28
  m: 4
  out_channels: 3

# path to save
paths:
  experiment_root: ./experiment

# optimizer
solver:
  lr: !!float 1e-3
  lr_steps:
    - 120
    - 240
    - 360
    - 480
  lr_gamma: !!float 0.5
  loss: mae
  epochs: 10
  workers: 8
  val_step: 1
  resume: ~
  resume_path: ~
  qat: ~
  qat_path: ~